### ISSUE TITLE
Global-buffer-overflow READ 4 (8097)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#182]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8097 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
==1==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000001759a7c at pc 0x000000d8152e bp 0x7f7dca5fe570 sp 0x7f7dca5fe568
--
  | READ of size 4 at 0x000001759a7c thread T1
  | SCARINESS: 17 (4-byte-read-global-buffer-overflow)
  | #0 0xd8152d in void scale_coefficients_internal<unsigned char>(thread_context*, int, int, int, int, int, int, bool, bool, int) libde265/libde265/transform.cc:0:48
  | #1 0xd682a8 in decode_TU(thread_context*, int, int, int, int, int, int, PredMode, bool) libde265/libde265/slice.cc:0:5
  | #2 0xd671d0 in read_transform_unit(thread_context*, int, int, int, int, int, int, int, int, int, int, int, int) libde265/libde265/slice.cc:3665:3
  | #3 0xd68c48 in read_transform_tree(thread_context*, int, int, int, int, int, int, int, int, int, int, int, PredMode, unsigned char, unsigned char) libde265/libde265/slice.cc:3963:5
  | #4 0xd68a09 in read_transform_tree(thread_context*, int, int, int, int, int, int, int, int, int, int, int, PredMode, unsigned char, unsigned char) libde265/libde265/slice.cc:3938:5
  | #5 0xd6b385 in read_coding_unit(thread_context*, int, int, int, int) libde265/libde265/slice.cc:4570:9
  | #6 0xd6405a in read_coding_quadtree(thread_context*, int, int, int, int) libde265/libde265/slice.cc:4633:7
  | #7 0xd6405a in read_coding_quadtree(thread_context*, int, int, int, int) libde265/libde265/slice.cc:4633:7
  | #8 0xd6c763 in decode_substream(thread_context*, bool, bool) libde265/libde265/slice.cc:4736:5
  | #9 0xd6dc84 in thread_task_ctb_row::work() libde265/libde265/slice.cc:4986:3
  | #10 0xd7a828 in worker_thread(void*) libde265/libde265/threads.cc:231:11
  | #11 0x7f7dce4bd6b9 in start_thread
  | #12 0x7f7dcdbd141c in clone /build/glibc-Cl5G7W/glibc-2.23/sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Links:
The line numbers appear to be broken in the oss-fuzz tooling.

Commit: 71030a752d47d66aa41bed6ab63db55f8372db1f
Testcase file: [clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5163584504987648.zip](https://github.com/strukturag/libde265/files/1998503/clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5163584504987648.zip)

**Comment by dlemstra** [comment]
Fixed
