### ISSUE TITLE
Null-dereference READ (11043)

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#217]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11043 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
SCARINESS: 10 (null-deref)
  #0 0xda8bbd in slice_segment_header::operator=(slice_segment_header const&) libde265/libde265/slice.h:130:7
  #1 0xda54ff in slice_segment_header::read(bitreader*, decoder_context*, bool*) libde265/libde265/slice.cc:416:13
  #2 0xd47f68 in decoder_context::read_slice_NAL(bitreader&, NAL_unit*, nal_header&) libde265/libde265/decctx.cc:626:27
  #3 0xd4d20f in decoder_context::decode_NAL(NAL_unit*) libde265/libde265/decctx.cc:1230:11
  #4 0xd4d69a in decoder_context::decode(int*) libde265/libde265/decctx.cc:1318:16
  #5 0xca3813 in libde265_v1_decode_image(void*, heif_image**) libheif/libheif/heif_decoder_libde265.cc:294:18
  #6 0xc6711d in heif::HeifContext::decode_image(unsigned int, std::__1::shared_ptr<heif::HeifPixelImage>&, heif_decoding_options const*) const libheif/libheif/heif_context.cc:929:11
  #7 0xc665cb in heif::HeifContext::Image::decode_image(std::__1::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_chroma, heif_decoding_options const*) const libheif/libheif/heif_context.cc:865:31
  #8 0xc411d2 in heif_decode_image libheif/libheif/heif.cc:576:33
  #9 0x9c649e in ReadHEICImageByID imagemagick/coders/heic.c:341:9
  #10 0x9c40f5 in ReadHEICImage imagemagick/coders/heic.c:465:10
  #11 0x5f10fa in ReadImage imagemagick/MagickCore/constitute.c:547:15
  #12 0x591259 in BlobToImage imagemagick/MagickCore/blob.c:475:13
  #13 0x4d4e74 in Magick::Image::read(Magick::Blob const&) imagemagick/Magick++/lib/Image.cpp:4028:12
  #14 0x4cafb9 in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:46:11
  #15 0x4cc27a in ExecuteFilesOnyByOne /src/libfuzzer/afl/afl_driver.cpp:216:5
  #16 0x4cc27a in main /src/libfuzzer/afl/afl_driver.cpp:253
  #17 0x7f5a2242f82f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/libc-start.c:291
  #18 0x421398 in _start
```

Links: 
https://github.com/strukturag/libde265/blob/9ffb59c2d51c53bd6d06a07b842d0cc0365a232d/libde265/slice.h#L130

Commit: 9ffb59c2d51c53bd6d06a07b842d0cc0365a232d
Testcase file: [clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5711659511840768.zip](https://github.com/strukturag/libde265/files/3341846/clusterfuzz-testcase-minimized-encoder_heic_fuzzer-5711659511840768.zip)

**Comment by alex** [comment]
Per https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11043 this is fixed and can be closed
